### PR TITLE
Added android support to ArrayList

### PR DESCRIPTION
**Pull request by DCampagnola**
Good morning,
I've added partial array list support

### CODE REVIEW

**Comment by DennisAlund** [comment]
What problem is this solving? Please open an issue that describes the problem and some sample of how to reproduce it so that the pull request is offering a solution.

**Comment by Zazo032** [comment]
This may fix https://github.com/oddbit/flutter_facebook_app_events/issues/19#issuecomment-683706979

**Comment by DennisAlund** [comment]
Could you please provide implementation for iOS/Swift also.

**Comment by DennisAlund** [comment]
Closed due to inactivity

**Pull request closed without merging**
