### PR TITLE
fix returntype and docs for getApplicationId

### LINKED ISSUE #48: getApplicationId not returning String
Getting the application id is not correctly exposed in 'FacebookAppEvents'. It should probably return a `String` value.

https://github.com/oddbit/flutter_facebook_app_events/blob/48669e246a0d46b61038cc2875b8451ac092e327/lib/facebook_app_events.dart#L52

Will see if I can put in a PR for this when I get a chance.

### PR DESCRIPTION
**Pull request by fstof**
fixes #48

### CODE REVIEW

**Comment by fstof** [comment]
Not sure if PR should be to `develop` or to `master` branch

**Comment by DennisAlund** [comment]
Thank you for your contribution, please bump the version to `0.6.1` and write a release note in [CHANGELOG.md](https://github.com/oddbit/flutter_facebook_app_events/blob/master/CHANGELOG.md) 

https://github.com/oddbit/flutter_facebook_app_events/blob/48669e246a0d46b61038cc2875b8451ac092e327/pubspec.yaml#L4

**Review by DennisAlund — CHANGES_REQUESTED** [review]
LGTM after updating the version number in `pubspec.yaml` and making release notes. Please check which current version is on `master` and update patch version accordingly.

**Comment by DennisAlund** [comment]
I'm changing the base branch and updating the `pubspec.yaml` myself. Thank you for your contributions 🙏

**Review by DennisAlund — APPROVED** [review]

**Comment by fstof** [comment]
sorry for not updating man, been a hectic week on my side.

Thank you 👍

**Pull request merged**
